image: python:3.9.7

stages:
  - build
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

buil api:
  stage: build
  script:
    - pip install -r requirements.txt
    - python api/surv/manage.py runserver &
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - ./api

test build:
  stage: test
  script:
    - pip install -r requirements.txt
    - python api/surv/manage.py runserver &
    - sleep 5
    - curl "http://localhost:8000" | tac | tac | grep -q "controls"

test api:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m pytest api/surv -s -v --durations=0 --cov=. -m "not skip_in_ci" --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

test fibonaci:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m pytest fibonacci -s -v --durations=0 --cov=. --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
